--- 
document: 
  description: |
    Report della ricerca e del processo di progettazione del modello di sito comunale e dei flussi di servizio disponibile su Designers Italia.
  name: "Documentazione di progetto per il modello di sito e servizi dei Comuni italiani"
  tags: 
    - siti web
    - design
    - comuni 
